# application_port: 8000
application:
  port: 8000
  # host: 127.0.0.1
# database:
#   host: "127.0.0.1"
#   port: 54322
#   username: "postgres"
#   password: "password"
#   database_name: "newsletter"